# Generated by Django 3.2.4 on 2021-07-04 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaguarete', '0009_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='brief_description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='long_description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
