# Generated by Django 3.2.4 on 2021-07-04 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaguarete', '0010_auto_20210704_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='long_description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
