# Generated by Django 3.2.4 on 2021-07-04 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaguarete', '0011_alter_product_long_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products_list',
            field=models.ManyToManyField(blank=True, default=[], to='jaguarete.Product'),
        ),
    ]
